### ISSUE TITLE
Turtle Serializer - BNode Syntax Possibly Incorrect

### ISSUE THREAD

**Issue by wagonhelm** [RDFLib/rdflib#1255]
I'm using RDFLib to create graphs then serialize them in ttl format to be [loaded by a wikidata query service / blazegraph](https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Loading_data).  I ran into errors loading triples with BNodes in the following format created by the turtle serializer:

`    ns2:P571 [ ] ;`

but blazegraph would accept the BNode with the empty character removed between brackets:

`    ns2:P571 [] ;`

My hacky/trial&error solution for the moment was to remove the ' ' from [here](https://github.com/RDFLib/rdflib/blob/c11f7b503b50b7c3cdeec0f36261fa09b0615380/rdflib/plugins/serializers/turtle.py#L389), but I was wondering if there is somehow I could do this without changing the source code, or, wanted to bring this to attention as a possible bug/feature request.  

Cheers,
Justin

**Comment by wagonhelm** [comment]
https://www.w3.org/TR/turtle/#unlabeled-bnodes leads me to believe that [] is the proper syntax for unlabelled blank nodes

**Comment by white-gecko** [comment]
This is a bug in blazegraph and should be reported there.
The Turtle grammar tells us, that there can be zero or more whitespaces: https://www.w3.org/TR/turtle/#grammar-production-ANON

[162s] | ANON | ::= | '[' WS* ']'
-- | -- | -- | --

Maybe it would be easy to remove the white space in our serialization, in order to react on the non-standard behavior of blazegraph but we can't know if there is any other non-standard implementation that relies on rdflib having the space :-\
