### ISSUE TITLE
transitive methods typo

### ISSUE THREAD

**Issue by jjon** [RDFLib/rdflib#1303]
While trying to understand some puzzling output from `graph.transitive_subjects()` I noted that the docstrings for graph.transitive_subjects and graph.transitive_objects (starting at graph.py line 882) are identical. I think perhaps this is not what was intended?

The puzzling output in question is as follows:
```
>>> pprint(list(cg.transitive_subjects(RDF.type, pome.Person)))
[rdflib.term.URIRef('http://prosopOnto.medieval.england/2006/04/pome#Person'),
 rdflib.term.URIRef('http://example.com/thisgraph#Hugh_Despenser'),
 rdflib.term.URIRef('http://example.com/thisgraph#Audley_Henry_de'),
 rdflib.term.URIRef('http://example.com/thisgraph#Thomas_earl_of_Warwick_d_1242'),
.
.
. etc.
]
```

The URI.ref for `pome.Person` is listed first even though it does not appear as a subject. Is this the intended behavior?

**Comment by white-gecko** [comment]
You are right about the docstrings, this must be a copy-paste error: https://github.com/RDFLib/rdflib/blob/d4c1effb5c4bfc0f0c24850ff0c3c3d5d5bea234/rdflib/graph.py#L882-L912
Also the signatures of both methods should be similar and we should use `predicate` in both cases (not `predicate` and `property`).

If you could propose a pull request for that, that could help.

Having the starting point of the transition as the first element of the output might not always be intuitive. By looking at the code, this is the behavior that is implemented by the recursive implementation. I think this is not very problematic, as you can just skip the the first element when working with the list. If this is not the case, could you please come up with a use case in which the current behavior is problematic?

**Comment by ashleysommer** [comment]
@white-gecko @aucampia 
I think you missed the main problem described in this issue.
The docstrings and signatures were incorrect, and that has been fixed, but outputs of transitive_subjects and transitive_outputs still contain a bug.
Its not a simple matter of "the output it contains the starting element, but I don't want the first element" with a response of "just skip the first element".

The problem is that **transitive_subjects** yields an _object_ as its first item, and **transitive_objects** yields a _subject_ as the first item.
Eg:
```
transitive_objects(ex:Me, foaf:knows)
--> ex:Me   # <- Incorrect
--> ex:Bob
--> ex:James
``` 

```
transitive_subjects(skos:narrower, ex:BlackSheep)
--> ex:BlackSheep  # <- Incorrect
--> ex:Sheep
--> ex:Vertebrate
``` 


that is not only unintuitive but actually incorrect behaviour. It doesn't matter that it is part of the recursion detection, there is no need to yield that. I will put in a PR to fix it.
