### ISSUE TITLE
GEO namespace missing from 6.0.0

### ISSUE THREAD

**Issue by timcroydon** [RDFLib/rdflib#1371]
I noticed the GEO namespace (http://www.opengis.net/ont/geosparql#) that was present in [earlier commits](https://github.com/RDFLib/rdflib/blob/83b3e99e6e4ed4cd6825773c24280373537b2ca9/rdflib/namespace.py#L380-L423) is no longer available in 6.0.0.

I know it's not part of SPARQL 1.1 itself, but are there any plans to reintroduce it, or is best to reimplement it myself locally as a `ClosedNamespace`?

**Comment by edmondchuc** [comment]
Hi @timcroydon, looks like the big pull request https://github.com/RDFLib/rdflib/pull/1074 to migrate `ClosedNamespace` to `DefinedNamespace` accidentally excluded the `GEO` namespace.

The new `DefinedNamespace` namespaces are now generated using this tool https://github.com/hsolbrig/definednamespace. If you want, feel free to give it a go and generate it for `GEO` and make a PR, otherwise I can give it a go when I have some time.

Alternatively, you can use the `Namespace`, `ClosedNamespace`, or `DefinedNamespace` classes and implement it yourself in your application code.

**Comment by timcroydon** [comment]
Thank you. I wasn't sure if its removal was an oversight or intentional.

I tried the tool suggested but I haven't immediately been able to get it running - I get a load of parsing errors like the following (using SKOS as an example):
```
owl:Ontology rdf:about="http://www.w3.org/2004/02/skos/core" does not look like a valid URI, trying to serialize this will break.
```
Not had time to investigate but will report back if I get time to try it properly.

In the meantime, if anyone needs a quick workaround, creating the following definition works fine:
```python
from rdflib import URIRef
from rdflib.namespace import ClosedNamespace

# GEO namespace was removed in RDFLib 6.0.0 so recreate it ourselves here
GEO = ClosedNamespace(
    uri=URIRef("http://www.opengis.net/ont/geosparql#"),
    terms=[
        "Feature",
        "Geometry",
        "SpatialObject",
        "asGML",
        "asWKT",
        "coordinateDimension",
        "defaultGeometry",
        "dimension",
        "ehContains",
        "ehCoveredBy",
        "ehCovers",
        "ehDisjoint",
        "ehEquals",
        "ehInside",
        "ehMeet",
        "ehOverlap",
        "gmlLiteral",
        "hasGeometry",
        "hasSerialization",
        "isEmpty",
        "isSimple",
        "rcc8dc",
        "rcc8ec",
        "rcc8eq",
        "rcc8ntpp",
        "rcc8ntppi",
        "rcc8po",
        "rcc8tpp",
        "rcc8tppi",
        "sfContains",
        "sfCrosses",
        "sfDisjoint",
        "sfEquals",
        "sfIntersects",
        "sfOverlaps",
        "sfTouches",
        "sfWithin",
        "spatialDimension",
        "wktLiteral",
    ],
)
```

**Comment by niklasl** [comment]
The parser error is since RDFLin 6.0 seems to have changed the default input format to `Graph.parse` from `application/rdf+xml` to `text/turtle`. While I know it is the modern way and more ideal (although one might suggest `TriG` is even more modern and ideal), I think it'll break a lot of existing code out there that just throws RDF/XML at the parser...

**Comment by timcroydon** [comment]
Sorry, should have been clearer - those errors were when I tried running the `definednamespace` tool (which is still on RDFLib 5.0.0) rather than when I try and use the output it generates. I'm almost certainly running it wrong though - will try again later.

**Comment by gjhiggins** [comment]
> those errors were when I tried running the `definednamespace` tool (which is still on RDFLib 5.0.0) rather than when I try and use the output it generates. I'm almost certainly running it wrong though - will try again later.

No, you're good. The `definednamespace` tool is slowly drifting out of scope - I had to put in a bit of effort to get it to work at all in an RDFLib 5.0.0 venv (but was eventually successful). I raised restorative PR #1622 in case the omission was inadvertent.
