### ISSUE TITLE
setup.cfg incorrectly specifies mypy should run on Python 3.6

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/rdflib#1513]
I was getting strange behavior from `mypy` failing on this one-liner program, but just when I was a `mypy` test in the `rdflib` source directory:

```python
from __future__ import annotations
```

Someone else having this problem [found it was user error](https://github.com/python/mypy/issues/9009#issuecomment-645459102), where they accidentally configured their environment to run in Python 3.6 where that one-liner wouldn't work.

Running `mypy --verbose` showed me `setup.cfg` was picked up for configuration, and that's where we see [this line](https://github.com/RDFLib/rdflib/blame/eb151d3b753ce9d705412228ee3b679852a22ef6/setup.cfg#L25).

From `tox.ini`, it seems at least this line should be revised to read Python 3.7.  Is this a one-liner patch to fix in `setup.cfg`, or is there something else that needs to happen between `setup.cfg` and/or `tox.ini` and/or `.drone.yml`?

**Comment by aucampia** [comment]
@ajnelson-nist I made a PR now to fix this, I presume you were working inside this repo, otherwise setup.cfg should not have an impact.

The right solution here is to change mypy config to be 3.7 I think, the python versions in `.drone.yml` and `tox.ini` say what version of python should run mypy, but the version in `[mypy]` section in `setup.py` says what version of python the code should be compatible with, and this basically controls the typing "feature set" - if you set mypy to use version 3.6, but run with python 3.7 - then mypy will still tell you typing and features that came in with python 3.7 are errors.

**Comment by ajnelson-nist** [comment]
Thank you for the quick fix!
