### ISSUE TITLE
json-ld will only be parsed from FILE, not from URL, not from STRING

### ISSUE THREAD

**Issue by klartext** [RDFLib/rdflib#1711]
json-ld Parsing from file works.
json-ld parsing from string does not work.
json-ld parsing via url does also not work.

The following is, what I get for parsing via URL from within a jupyter notebook:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/rdflib/plugin.py:124, in get(name, kind)
    123 try:
--> 124     p: Plugin[PluginT] = _plugins[(name, kind)]
    125 except KeyError:

KeyError: ('application/xml', <class 'rdflib.parser.Parser'>)

During handling of the above exception, another exception occurred:

PluginException                           Traceback (most recent call last)
Input In [15], in <module>
      1 url = "https://portal.issn.org/resource/ISSN/0265-0762?format=json"
      3 webgraph = Graph()
----> 4 webgraph.parse(url)

File ~/.local/lib/python3.10/site-packages/rdflib/graph.py:1255, in Graph.parse(self, source, publicID, format, location, file, data, **args)
   1253         format = "turtle"
   1254         could_not_guess_format = True
-> 1255 parser = plugin.get(format, Parser)()
   1256 try:
   1257     # TODO FIXME: Parser.parse should have **kwargs argument.
   1258     parser.parse(source, self, **args)  # type: ignore[call-arg]

File ~/.local/lib/python3.10/site-packages/rdflib/plugin.py:126, in get(name, kind)
    124     p: Plugin[PluginT] = _plugins[(name, kind)]
    125 except KeyError:
--> 126     raise PluginException("No plugin registered for (%s, %s)" % (name, kind))
    127 return p.getClass()

PluginException: No plugin registered for (application/xml, <class 'rdflib.parser.Parser'>)
```

**Comment by klartext** [comment]
[rdflib-check.py.zip](https://github.com/RDFLib/rdflib/files/8035288/rdflib-check.py.zip)

Zipped python file to check the three ways of parsing.

**Comment by gjhiggins** [comment]
> json-ld Parsing from file works. json-ld parsing from string does not work. json-ld parsing via url does also not work.

The JSON-LD parser works in all three cases. You're experiencing ancillary issues to do with i) RDFLib not being able to guess the format and ii) apparently not correctly handling the returned "application/json" Content-Type header.

This should work for you (JSON-LD is a context-aware format so should be read into a correspondingly context-aware RDFLib Dataset):
```py
ds = Dataset()
ds.parse(location="https://portal.issn.org/resource/ISSN/0265-0762?format=json", format="json-ld")
```
and also this:
```py
import urllib
jsonldstring = urllib.request.urlopen("https://portal.issn.org/resource/ISSN/0265-0762?format=json").read()
ds = Dataset()
ds.parse(data=jsonldstring, format="json-ld")
```

**Comment by gjhiggins** [comment]
I stepped through the process - RDFLib makes the request correctly advertising that it's prepared to accept (amongst other formats) "application/ld+json":
```py
{'User-agent': 'rdflib-6.2.0-alpha (http://rdflib.net/; eikeon@eikeon.com)',
 'Accept': 'application/rdf+xml, text/n3, text/turtle, application/n-triples, + \
            application/ld+json, application/n-quads, application/trix, application/trig'}
```

but bizarrely, the returned Content-Type isn't amongst the Accept members:
```py
[('Date', 'Wed, 09 Feb 2022 20:18:12 GMT'), ('Server', 'Apache/2.4.25 (Debian)'),
 ('X-Drupal-Cache', 'MISS'), ('Expires', 'Sun, 19 Nov 1978 05:00:00 GMT'),
 ('Cache-Control', 'no-cache, must-revalidate'), ('X-Content-Type-Options', 'nosniff'),
 ('Access-Control-Allow-Origin', '*'), ('Vary', 'Accept-Encoding'),
 ('Content-Length', '3455'), ('Connection', 'close'),
 ('Content-Type', 'application/xml; charset=utf-8')
]
```
and moreover, doesn't match `curl -I`:
```
HTTP/1.1 200 OK
Date: Wed, 09 Feb 2022 18:33:16 GMT
Server: Apache/2.4.25 (Debian)
X-Drupal-Cache: MISS
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: no-cache, must-revalidate
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
```

But, **from the data given**, RDFLib is working correctly - and from what I'm given to understand, this is par for the course with the dark art of remote HTTP-accessed resources.

**Comment by klartext** [comment]
The dark art, aha.
I think that's the thing behind the "why some people think, the web is broken" story.

There is an example for "Reading remote RDF" from https://rdflib.readthedocs.io/en/stable/intro_to_parsing.html

```
from rdflib import Graph

g = Graph()
g.parse("http://www.w3.org/People/Berners-Lee/card")
print(len(g))
```
It was not mentioned, that it will not work with json-ld. So the example is at least misleading.

From a user perspective, parsing fails; if it's internally not the parser, that is interesting for implementors, but not for the users, especially not when just starting to use the library and getting examples that imply automatic detection of filetype. (Looks like the example is from the marketing department, not from the teaching department.)

In the end I could do the parsing using string data with the call
```graphobj.parse(data=my_rdf_string, format="json-ld")```
where my_rdf_string contains the data, which I got from the server.
This works for me, but the issue was about using URLs, so it is not resolved.

The stuff thrown by the exception was not helpful to me (just using that library).
Was it helpful for the library developers? I have to let this question unanswered.

But it was somehow "funny" to find a ```# TODO FIXME: Parser.parse should have **kwargs argument.``` in the output. Maybe that was helpful to the library developers, I don't know. ;-)

**Comment by gjhiggins** [comment]
First off, I accept all your points regarding your user experience and note that there is a long-standing intention of [improving/revising the documentation](https://github.com/RDFLib/rdflib/discussions/1564) that you may care to contribute to. There is a certain tension between documenting RDFLIb in its main role as "a library for working with RDF" and documenting the application-level functionality because the information requirements of Python programmers using the library functions differ substantially from those of users using RDFLib at the application level.

> The dark art, aha. I think that's the thing behind the "why some people think, the web is broken" story.

As an example of the complexities, have a look at [WHATWG's take on conneg](https://wiki.whatwg.org/wiki/Why_not_conneg)

But I should address some infelicities that may mislead others ...

> There is an example for "Reading remote RDF" from https://rdflib.readthedocs.io/en/stable/intro_to_parsing.html
> ```
> from rdflib import Graph
> 
> g = Graph()
> g.parse("http://www.w3.org/People/Berners-Lee/card")
> print(len(g))
> ```
> 
> It was not mentioned, that it will not work with json-ld. So the example is at least misleading.

I know it's not what you meant but the example *works* as is and the n3 content-type is successfully determined from the returned Content-Type header.

```
$ curl -I https://www.w3.org/People/Berners-Lee/card
HTTP/2 200 
date: Tue, 15 Feb 2022 10:22:41 GMT
...
Content-Length, Accept
content-type: text/n3; qs=0.89
```

I imagine that you expected the example to work with any URL and yes, the documentation will be updated to explain further that this example is specific.

> From a user perspective, parsing fails; if it's internally not the parser, that is interesting for implementors, but not for the users, especially not when just starting to use the library and getting examples that imply automatic detection of filetype. (Looks like the example is from the marketing department, not from the teaching department.)

Automatic detection of filetype is not implied, the documentation preceding that example is reasonably clear about filetypes and explicitly uses the word "guess":

> “RDFLib can ***guess*** what format the file is by the file ending (“.nt” is commonly used for n-triples) so you can just use [parse()](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.Graph.parse) to read in the file. If the file had a non-standard RDF file ending, you could set the keyword-parameter format to specify either an Internet Media Type or the format name (a list of available parsers is available).”

fwiw, automatic detection of remotely-served content-type is [not trivial and unreliable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#mime_sniffing). 

> In the end I could do the parsing using string data with the call `graphobj.parse(data=my_rdf_string, format="json-ld")` where my_rdf_string contains the data, which I got from the server. This works for me, but the issue was about using URLs, so it is not resolved.

In the *reported* issue, the content-type advertised by the server was `application/xml` which did not match the content-type of the json-ld content. The content was successfully parsed when an explicit format was given.
 
> The stuff thrown by the exception was not helpful to me (just using that library). Was it helpful for the library developers? I have to let this question unanswered.

For a developer using the library, the exception: `KeyError: ('application/xml', <class 'rdflib.parser.Parser'>)` is informative in that it communicates the fact that the content type was served as `application/xml` instead of the expected `application/json-ld`.

> But it was somehow "funny" to find a `# TODO FIXME: Parser.parse should have **kwargs argument.` in the output. Maybe that was helpful to the library developers, I don't know. ;-)

Yes it is helpful to the library developers. And it's not the only instance of a `# TODO` in that code - it's just one way in which communities of volunteer FOSS developers communicate to and between themselves.

**Comment by nicholascar** [comment]
Just wanted to add: I'm not keen on always assuming that JSON is JSON-LD in RDFLib due to other JSON-based serializations of RDF, e.g. [HexTuples](https://github.com/ontola/hextuples) which RDFLib supports. I prefer to see a clear indication of JSON-LD from sources like use of the official JSON-LD Media Type, `application/ld+json`.

Having said that, in my own use of RDFLib, my extensions to the `guess_format` function that peek inside data or a file look for `[` or `{` and assume that's JSON-LD or `["` and assume that's HexTuples. I should probably improve those rules...

**Comment by gjhiggins** [comment]
closing as no further action is indicated
