### ISSUE TITLE
6.2.0: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [RDFLib/rdflib#2035]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

**Comment by kloczek** [comment]
Here is pytest output 
[python-rdflib-pytest-log.txt](https://github.com/RDFLib/rdflib/files/9128854/python-rdflib-pytest-log.txt)

**Comment by aucampia** [comment]
@kloczek this is a known issue: https://github.com/RDFLib/rdflib/issues/1847

To fix it, don't run tests with lxml installed.

**Comment by aucampia** [comment]
RDFLib has a bug which is tracked in https://github.com/RDFLib/rdflib/issues/1847 - and because of this bug, using lxml with XML based SPARQL results fail.

We should fix the bug, but we should also mark the tests in our test suite that are known to fail under some conditions with xfail under those conditions, so that the test suite still passes.

For example:

https://github.com/RDFLib/rdflib/blob/d2630095bf242f7dd3a678d864b479e97e36de5a/test/test_w3c_spec/test_n3_w3c.py#L117-L119

This test is known to fail on windows, so we mark it with xfail on windows.

Similarly, with lxml installed, the failing tests here should have an xfail marker.

**Comment by kloczek** [comment]
Thank you very much for the explanation 😄
