### ISSUE TITLE
Turning rdflib jsonld into a "full processor" (a.o. for schema.org compliance)

### ISSUE THREAD

**Issue by ghost** [RDFLib/rdflib#2692]
Cloned from https://github.com/RDFLib/rdflib-jsonld/issues/62 :

The JSON-LD 1.1 draft spec mentions different levels of processing for JSON-LD: https://w3c.github.io/json-ld-syntax/#processor-levels

A pure processor can only parse JSON-LD expressed in JSON directly, but a full processor can also parse JSON-LD embedded in HTML.

It would be great if rdflib-jsonld would support this. It would make rdflib-jsonld a library that could be used for HTML documents following the schema.org guidelines for embedding (meta)data in HTML pages as described in their getting started guide https://schema.org/docs/gs.html.

Together with the RDFa & microdata parsers this can then work as a fully RDF based version of the Structured Data Testing tool from Google: https://search.google.com/structured-data/testing-tool.

**Comment by wallberg-umd** [comment]
I'm looking into implementing this using https://github.com/RDFLib/rdflib-jsonld/pull/63 as a starting point.  In that code HTML parsing is attempted after JSON parsing fails, but I'm looking at choosing the parse using the content type of the source.

I see that the the JSON-LD test suite in "test/jsonld/1.1" already provides a number of tests which just need to be enabled.

**Comment by wallberg-umd** [comment]
FYI: I'm occasionally working on this at https://github.com/wallberg-umd/rdflib/tree/issue-2692-embedded-jsonld-draft . I've added the basic functionality and enabled the existing tests.  I'm now working through making the tests pass.

**Comment by wallberg** [comment]
I've completed an initial implementation for this issue, see https://github.com/wallberg/rdflib/tree/issue-2692-embedded-jsonld .

It contains one breaking change: when `rdflib.plugins.shared.jsonld.util.source_to_json` extracts JSON-LD from HTML, it needs to return the value of the HTML base element in addition to the JSON.  I took the simplest path and returned a tuple containing the JSON and the base.  

I can think of other ways to return the base without breaking the current return value:
1) Return `json` when processing a json document and `(json, base)` when processing an html document.
2) Add an optional parameter to return `(json, base)` instead of `json`.
3) Continue returning only `json`, but add an optional parameter which will receive the value of `base`.

I'd like to get some feedback on the preferred approach before submitting the PR.

A note on the current status of validation:
1) `task test` passes
2) `task lint` passes
3) `task mypy` fails, I believe to existing problems in main
4) `poetry run python -m mypy rdflib/plugins/parsers/jsonld.py rdflib/plugins/shared/jsonld/context.py rdflib/plugins/shared/jsonld/util.py test/jsonld/runner.py test/jsonld/test_context.py test/jsonld/test_onedotone.py` passes
