### ISSUE TITLE
Add method for adding new Seq objects

### ISSUE THREAD

**Issue by gromgull** [RDFLib/rdflib#280]
For querying - we have the `Seq` class / `Graph.seq` method for RDF Seq's and the `Graph.items` for RDF collections

The `collections.Collection` class tries to help adding collections, although it's slightly broken (#223)

We have no easy way to add seqs...

**Comment by gromgull** [comment]
A collection adding method was added. 

Related is, why do we not have a Bag or Alt class?

**Comment by kushagr08** [comment]
I am interested in solving this issue. Is a separate class wanted for bag/alt, since the Collection class only handles Seq?

**Comment by ashleysommer** [comment]
@kushagr08 
It might be a good idea to refactor the Collection class such that it uses rdf:Bag, then add subclasses for rdf:Seq and rdf:Alt. This would be a breaking change, but is a logical change, and would be considered for the 6.0.0 release.

**Comment by kushagr08** [comment]
@ashleysommer 
The Collection class is being used in various other sections of code such as graph.py . So if I remodel it as a Bag class, would I need to do corresponding changes in other sections of the code which use this class?  Or will it be a good idea to make a Bag class from scratch and let the Collection class remain as it is ? This is because a bag is structurally different from a Collection.

**Comment by hsolbrig** [comment]
Don't know whether this is directly applicable, but something we've found handy in certain situations:

https://github.com/hsolbrig/CFGraph

**Comment by kushagr08** [comment]
@ashleysommer @hsolbrig 
The structure of a collection in RDF is fundamentally different from that of a container. 
A collection node has rdf: first which has the value of the current node and rdf :rest which points to the rest of the list.
A container, on the other hand, has one blank node which points to all of it's items by predicates of the form of rdf:_1 ,rdf:_2 and so on.
Therefore, I propose to add a separate container class to close this issue (as collection class is already there). Whether the container will be seq, alt or bag is for the user to decide since all of seq, alt and bag are containers, structurally same and semantically different. (https://stackoverflow.com/questions/29001433/how-rdfbag-rdfseq-and-rdfalt-is-different-while-using-them)

**Comment by kushagr08** [comment]
@ashleysommer @hsolbrig 
I have made a pull request for this issue. I have added a Container class with its 3 subclasses corresponding to seq, alt and bag as proposed. I have added some test cases also using assert statements. I request you to review the same.
