### ISSUE TITLE
Make dependabot updates to a different target-branch

### ISSUE THREAD

**Issue by ashleysommer** [RDFLib/rdflib#2836]
My intention is to create a new "bot-updates" branch for dependabot to target its PRs.
Related to #2835 

This means we can merge multiple updates to the same branch while ignoring CI failures, we will not worry about lockfile problems. This means we don't block other PRs from running CI due to bad lockfile issues.
We can periodically create a new working lockfile from the `bot-updates` branch and push the new `pyproject.toml` and matching working `poetry.lock` file from that branch into `main` when we are ready.

Thoughts?

**Comment by nicholascar** [comment]
Any automation or grouping of the small updates is good since we do need to roll them in, but we don't have to have them all hanging around all the time individually.

Are all dependabot and similar PRs flagged in such a way - labels etc. - that we could write a GH Action to deal with them automatically whether on the `main` branch or another?

**Comment by nicholascar** [comment]
This Issue has been bypassed by getting a handle on dependabot PRs generally
