### ISSUE TITLE
Expected behaviour of `Dataset.triples`? I think it always returns an empty list

### ISSUE THREAD

**Issue by WhiteGobo** [RDFLib/rdflib#2959]
This is a question related to issue #2958 . During sparql evaluation `graph.triples` is used to find triples in context.

So with given data, no triples are returned. Dataset doesnt has any identifier, so it should return all available triples right?

```python
from rdflib import *

GraphString = '''

PREFIX eg: <http://example.com/person/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

eg:graph-1 {
    eg:drewp a foaf:Person .
    eg:drewp eg:says "Hello World" .
}

eg:graph-2 {
    eg:nick a foaf:Person .
    eg:nick eg:says "Hi World" .
}
'''

g = Dataset()
g.parse(data=GraphString, format="trig")
print(list(g.triples((None, None, None))))
```

**Comment by ashleysommer** [comment]
Hi @WhiteGobo 

In your example file, there are two named graphs, and no default graph.

a) If `ds.default_union` is False, then `ds.triples((None, None, None))` will give you the triples from the default graph, which there are none.
b) If  `ds.default_union` is True, then `ds.triples((None, None, None))` will give you all triples from all named graphs.

Two things to point out.

1) You've mentioned the Dataset itself doesn't have any identifier, that doesn't matter because `identifier` attribute for a `Dataset` in RDFLib was deprecated in RDFLib v6.0. Identifiers are only for named graphs, and it doesn't make sense in the context of an Dataset to have an identifier, so its usage was deprecated.

2) This Graph/ConjunctiveGraph/Dataset API surface is well past due for refresh.
When RDFLib was first developed in 2003, the RDF v1.0 spec was still being written only Graphs existed. RDFLib v1.1 with the concept of Datasets wasn't introduced until 2014. In those 11 years, 2003-2014 RDFLib introduced ConjunctiveGraph as a new feature but never made it into any RDF spec.
Unfortunately the way it was implemented was that ConjunctiveGraph was a hacked-on extension to Graph, and in 2014 Dataset was a hacked-on extension to ConjunctiveGraph. That is why Datasets are a confusing mess.
We are planning a major rewrite of the implementation of Graphs and Datasets (and removal of ConjunctiveGraph) for RDFLib v8 later this year, so it will be a better experience then.

**Comment by ashleysommer** [comment]
Here is some code to illustrate the behaviour of `ds.triples()`
Note, I added two triples to the unnamed default graph in the trig file too.

```python3
from rdflib import *

GraphString = '''
PREFIX eg: <http://example.com/person/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

eg:graph-1 {
    eg:drewp a foaf:Person .
    eg:drewp eg:says "Hello World" .
}

eg:graph-2 {
    eg:nick a foaf:Person .
    eg:nick eg:says "Hi World" .
}

eg:ash a foaf:Person .
eg:ash eg:says "Default" .
'''

ds = Dataset()
ds.parse(data=GraphString, format="trig")
ds.default_union = False
print(list(ds.triples((None, None, None))))
# returns only the triples from the "default" graph:
# > eg:ash a foaf:Person 
# > eg:ash eg:says "Default" 
print(list(ds.triples((None, None, None, URIRef("http://example.com/person/graph-1")))))
# Returns only from "graph-1" named graph:
# > eg:drewp a foaf:Person 
# > eg:drewp eg:says "Hello World" 
ds.default_union = True
print(list(ds.triples((None, None, None))))
# with default_union=True it returns everything
# > eg:drewp a foaf:Person 
# > eg:drewp eg:says "Hello World" 
# > eg:nick a foaf:Person 
# > eg:nick eg:says "Hi World" 
# > eg:ash a foaf:Person 
# > eg:ash eg:says "Default" 

```

**Comment by WhiteGobo** [comment]
ok thx for the explanation. This solves the problem.

**Comment by drewp** [comment]
Bit me again today. Any chance Dataset() could require the default_union arg? Or raise a warning if you don't set it explicitly?

**Comment by edmondchuc** [comment]
This is currently planned for v8 (see https://github.com/RDFLib/rdflib/issues/3302).
