### ISSUE TITLE
turtle literal loses precision info

### ISSUE THREAD

**Issue by satra** [RDFLib/rdflib#608]
this line in the serializer causes turtle output to lose datatype info
https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/serializers/turtle.py#L304

```
from rdflib.term import Literal
from rdflib.namespace import XSD
print(Literal(10, datatype=XSD.decimal)._literal_n3(use_plain=True))
print(Literal(10, datatype=XSD.decimal)._literal_n3(use_plain=False))
```
results in:
```
10.0
"10"^^<http://www.w3.org/2001/XMLSchema#decimal>
```

in the first scenario the round trip loses the info that the value is a decimal with no '.0', simply '10'

**Comment by satra** [comment]
actually this is happening because of this line:

https://github.com/RDFLib/rdflib/blob/master/rdflib/term.py#L1206

why is '.0' being added for a decimal? if it is to distinguish from an integer, it should be qualified - i.e. use_plain should be set to False.

i can send a PR to fix this, if this seems reasonable.

**Comment by satra** [comment]
essentially this is the fix:

```
diff --git a/rdflib/term.py b/rdflib/term.py
index 561c3e6..101b6dd 100644
--- a/rdflib/term.py
+++ b/rdflib/term.py
@@ -1203,9 +1203,8 @@ class Literal(Identifier):
                     return sub("\\.?0*e", "e", u'%e' % float(self))
                 elif self.datatype == _XSD_DECIMAL:
                     s = '%s' % self
-                    if '.' not in s:
-                        s += '.0'
-                    return s
+                    if '.' in s:
+                        return s
 
```

**Comment by joernhees** [comment]
hmm, that code is pretty old and it's in a private method, which you're using in a way that actually asks it to "throw away the datatype". My guess is that the intention of that old snippet is to make round-tripping safer (so parsing the n3 of a decimal will at least not lead to an int). Also as `Decimal('10') == Decimal('10.0')`, it seems perfectly safe to me.

So my call is that this would be a rather cosmetic change which is slightly more dangerous in the general case (you could suddenly end up with integer division for example), which is why i'll close this for now. 

Also if you used this (private!) method for formatting, then it's probably a better idea to do this explicitly (and as you like) in your code. If you were simply searching for a datatype preserving method, you can just do `Literal(10, datatype=XSD.decimal).n3()`.

Feel free to reopen.

**Comment by satra** [comment]
@joernhees - i used the private function, mostly because that's what gets called in the serializer inside rdflib. i'm not actually using that private function in my code.

i was writing some round trip code that takes  decimal specified as 10 writes it out and reads back in and checks for equality.  well the check happens a layer later and that was running into an error if i didn't specify the data type. 

i'll dig into it some more and reopen if necessary. it's possible that the error happens because `str(Decimal('10')) != str(Decimal('10.0'))`

**Comment by satra** [comment]
so the issue is indeed with the lexical representation in the prov library. i've posted an issue there.
