### ISSUE TITLE
support for xsd:duration

### ISSUE THREAD

**Issue by wrobell** [RDFLib/rdflib#629]
The script below gives output

```
[(rdflib.term.URIRef('file:///home/wrobell/projects/uddo/#c1'), None),
 (rdflib.term.URIRef('file:///home/wrobell/projects/uddo/#c2'), None)]
```

It would be nice to get time difference as xsd:duration instead of nulls.

The script

```
from pprint import pprint
import rdflib
import io

data = """
@prefix : <#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

:C a rdfs:Class.

:start a rdf:Property;
    rdfs:domain :C; 
    rdfs:range xsd:dateTime.

:end a rdf:Property;
    rdfs:domain :C; 
    rdfs:range xsd:dateTime.

:c1 a :C;
    :start "2016-01-01 20:00:00"^^xsd:dateTime;
    :end "2016-01-02 20:01:00"^^xsd:dateTime.

:c2 a :C;
    :start "2016-01-01 20:05:00"^^xsd:dateTime;
    :end "2016-01-01 20:30:00"^^xsd:dateTime.
"""

graph = rdflib.Graph()

f = io.StringIO(data)
graph.parse(f, format='n3')

result = graph.query("""
SELECT ?c ?duration
WHERE {
    BIND(?end - ?start AS ?duration)
    ?c :start ?start;
        :end ?end.
}
""")

pprint(list(result))
```

**Comment by gromgull** [comment]
SPARQL only defines - + etc for numeric types: https://www.w3.org/TR/sparql11-query/#OperatorMapping

Note that raw literals in RDFLib also do not support arithmetic: 

```python
In [110]: l1=rdflib.Literal(datetime.now())

In [111]: l2=rdflib.Literal(datetime.now())

In [112]: l1-l2
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-112-fe8dcc4af6cc> in <module>()
----> 1 l1-l2

TypeError: unsupported operand type(s) for -: 'Literal' and 'Literal'
```

(Although we support +, but in lexical space: 
```python
In [113]: l1+l2
Out[113]: rdflib.term.Literal(u'2017-01-19T15:11:29.4567162017-01-19T15:11:32.352804', datatype=rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#dateTime'))


In [114]: rdflib.Literal(1) + rdflib.Literal(2)
Out[114]: rdflib.term.Literal(u'12', datatype=rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#integer'))
```
🙈
)

BUT! That doesn't mean we cannot extend it! Ideally we implement the operators for all typed literals (see https://github.com/RDFLib/rdflib/pull/451), and then we expose it in SPARQL. 

This would be very nice, but is not really a blocker for 4.2.2, moving to 5.0

**Comment by Akash-Sharma-1** [comment]
Hi! Can I work on this issue? Seems interesting to me. Just waiting for the green light from the maintainers and contributors.

**Comment by JervenBolleman** [comment]
@Akash-Sharma-1 yes you can work on this! I suspect the area you need to add code to is https://github.com/RDFLib/rdflib/blob/bd8215077840c634aa67cefa1a9fe56a1d945c3c/rdflib/plugins/sparql/operators.py#L755
But I am not sure.

Also see https://github.com/w3c/sparql-12/blob/master/SEP/SEP-0002/sep-0002.md

**Comment by Akash-Sharma-1** [comment]
Thanks for the information @JervenBolleman. 👍  
Yes, I was also expecting to work in this part of the code.

**Comment by Akash-Sharma-1** [comment]
Hi! 
So, I have been working on this issue for quite some time. I have extended the handling of arithmetic operations (addition/subtraction) of dates, times and durations for SPARQL queries.  

So far, I have implemented and tested out these operations on my local code which are also mentioned here - (https://github.com/w3c/sparql-12/blob/master/SEP/SEP-0002/sep-0002.md) (@JervenBolleman  thanks again for the link)
The above SPARQL query of the issue also works well with the fix.

I wanted to discuss some points regarding these operations before finalizing the PR:
1.  Would it be beneficial, to handle multiple operands for these operations in the query similar to numeric types?
For example, _`(datetime1 - datetime2 - dateTime3)`_ or _`(dateTime1 - dayMonthDuration1 - dayMonthDuration2)`_  
These type of multiple operands operations are however not discussed in w3c SPARQL.
2. In cases of subtraction of dates or dateTimes, if the first date is earlier to the second date then the resulting duration comes out to be negative. Since negative `xsd:duration` is valid, I am allowing this case in my code. Would it be helpful if I notify the user about the subtraction from smaller date?
An example of this case, ` "2016-01-01T20:00:00"^^xsd:dateTime -  "2016-01-02T20:01:00"^^xsd:dateTime` would result in  `"-P1DT1M"^^xsd:duration`

**Comment by nicholascar** [comment]
@Akash-Sharma-1 

My personal answers to your questions (i.e. not anything official from all of RDFlib!):

1. Yes! Just as *normal* maths allow multiple operands, I think this is expected, but certainly not required, behaviour

2. I wouldn't bother warning the user, they'll see the negative result. If they want to be warned, they could write a check in their application code. As you say, negative `xsd:duration` is valid

**Comment by Akash-Sharma-1** [comment]
@nicholascar 
Thank you for responding.
Yes, I couldn't agree more with your points, that does make sense. 
Ok then, keeping in mind these points, I'll finalize the PR and submit it soon. 👍

**Comment by Akash-Sharma-1** [comment]
Hi @nicholascar , @JervenBolleman !
So, as discussed I have added #1061 for handling the DateTime related arithmetic operations for SPARQL queries. (The master-merge and conflict-resolution for this are also completed.)
Additionally, I have also added #1089 to handle these DateTime related arithmetic operations for raw Literals also. 
I have also added testing modules for both the feature additions in their respective PRs. 

I would request you to kindly review the PRs.
Thank you! 😊
