### ISSUE TITLE
Sum of conjunctive graphs is not conjunctive graph

### ISSUE THREAD

**Issue by wrobell** [RDFLib/rdflib#652]
Sum of conjunctive graphs is not conjunctive graph

```
>>> g1 = ConjunctiveGraph()
>>> g2 = ConjunctiveGraph()
>>> type(g1 + g2)
rdflib.graph.Graph
```

Is it a bug?

Workaround

```
>>> graph = ConjunctiveGraph()
>>> graph += g1
>>> graph += g2
>>> type(graph)
rdflib.graph.ConjunctiveGraph
```

**Comment by joernhees** [comment]
hmm, i agree that this is somewhat surprising, but i can see why it's more "careful" than returning a ConjunctiveGraph: ConjunctiveGraphs represent their default graph as BNode if not specified otherwise. Adding any two ConjunctiveGraphs will now have two such "default graphs"... which one is the default then?

**Comment by gromgull** [comment]
Maybe generate a new BNode for the new graph?

**Comment by joernhees** [comment]
would it be correct to move the triples from the former 2 default graphs to that new BNode default graph?

**Comment by mielvds** [comment]
With some time left, I added a test case in #2557. I cannot reproduce the above, so maybe it's fixed by now?

**Comment by aucampia** [comment]
- Closed by https://github.com/RDFLib/rdflib/pull/2557
