### ISSUE TITLE
Parse of IRIs fails with error 'does not look like a valid URI, trying to serialize this will break.'

### ISSUE THREAD

**Issue by g20ready** [RDFLib/rdflib#703]
As stated at [rdf11-primer](https://www.w3.org/TR/2014/NOTE-rdf11-primer-20140225/) a resource should be identified by an IRI.

**Comment by gromgull** [comment]
1. this is just a warning, as it says, it will produce illegal output when serialised, but if you never intend to serialise your data, just pretend it never happened. 

2. can we see an example of the IRI causing this?

**Comment by g20ready** [comment]
I see. Here is a sample. 
```
http://yago-knowledge.org/resource/John_"Jabo"_Starks does not look like a valid URI, trying to serialize this will break.
```
I can provide you with more samples if needed. 

Is there any way to mute this output?

**Comment by joernhees** [comment]
`"` is not a valid char in a URI, it needs to be escaped...

**Comment by g20ready** [comment]
Indeed but yago database is not using URIs but IRIs.

I guess that as long as the IRI is loaded in the graph its ok. Any way to mute the warning?

**Comment by joernhees** [comment]
why guess... read the IRI spec please: https://tools.ietf.org/html/rfc3987#section-2.2

`"` is neither valid for IRIs nor URIs.

You think you might want to disable that warning, but as the people who put it there, we're strongly suggesting to use proper URIs (/IRIs) instead, as otherwise "trying to serialize this will break". If you still think that you know better, no one is stopping you from having a look at the python `warnings` docs...

**Comment by gromgull** [comment]
if you enter that URL into your browser, the browser encodes it for you, and the resulting openlinksw virtuoso page shows the correctly encoded IRI/URI: `http://yago-knowledge.org/resource/John_%22Jabo%22_Starks `

**Comment by g20ready** [comment]
Yes, that i know. But in my case, I load the contents of a big n3 file (downloaded from [yago](http://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/yago/downloads/)) into the graph. The file contains many triples with unescaped characters. I didn't notice at first. And when i noticed I thought its ok. But after a bit of research i understood its probably a mistake. Thanks.

**Comment by teledyn** [comment]
I can understand the caution with some of the un-escaped examples given here so far, but I'm seeing this warning with urls such as https://www.factorydirecthardware.com/parmir-ssv-220a-single-handle-single-hole-vanity-faucet-with-cover-plate.html#Offer which is maybe a tad long, but looks perfectly compliant to me.  What am I overlooking?

**Comment by sanderzz91** [comment]
Idem. I get this warning on the URI http://company.project.ourcompany.com/device/some-device-123456/device-interface/D15 and I intend to serialize my graph.

**Comment by sanderzz91** [comment]
Update: the warning that is printed is just not complete.
I got this problem because of this:
```
from rdflib import Graph, Namespace

g = Graph()
ns = Namespace('http://company.project.ourcompany.com/')
device = ns['device/some-device-123456']
interface_name = 'D15 Input'
interface = ns['device-interface/' + device_interface_name]
g.add( (device, ns.hasInterface, interface) )
```

The error should have been `-->http://company.project.ourcompany.com/device/some-device-123456/device-interface/D15 Input<--- does not look like a valid URI, trying to serialize this will break.`

I solved this by using the urllib package in the second last line of the above example as below.

```
from urllib.parse import quote
interface = ns[quote('device-interface/' + device_interface_name)]
```
