### ISSUE TITLE
Standard distribution (sdist) for 4.2.2.1 

### ISSUE THREAD

**Issue by papachoco** [RDFLib/rdflib#706]
Hi,

Is there any way you could release an sdist for 4.2.2.1 to match the wheel version?

Thanks

Carlos

**Comment by joernhees** [comment]
hmm, i knew this would backfire...

short answer: there is no 4.2.2.1, not even in the wheel, it was just a means of putting a correct py2 wheel on pypi after i had made a stupid mistake with the original one (it picked up the sdist that ran through 2to3 for py3, and thus failed on py2). I deleted that one within a few minutes after the release, but due to pypi restrictions now can't replace it with another 4.2.2 wheel.

If you don't believe me, see `pip freeze`. The version part of the filenames for wheels are actually just "smoke"... The actual version is inside the `metadata.json` file inside the wheel: `less rdflib-4.2.2.1-py2-none-any.whl:rdflib-4.2.2.dist-info/metadata.json`.

That said, what `rdflib-XXX-py2-none-any.whl` with `XXX` different from 4.2.2 would not have confused you? Would 4.2.2.0 be better?

I'll not make a 4.2.3 release for this, before that i'll just remove the py2 wheel and say they'll be provided with 5.0.0.

**Comment by joernhees** [comment]
ok, after discussions i decided: there's no py2 wheel for 4.2.2 anymore.

It's the element of least surprise, no confusing weird filename, and the sdist install doesn't do anything complicated and is quite fast as well. py3 still comes with a wheel.
