### ISSUE TITLE
URIRef comparison with Python `str` fails using `==`

### ISSUE THREAD

**Issue by luav** [RDFLib/rdflib#773]
URIRef comparison with Python `str` fails in both Python v2 and v3.  
Per-char comparison of URIRef with str and `==` yield distinct values:
```python
import rdflib
from rdflib.namespace import RDF
typeProp = '<' + RDF.type + '>'  # N3/quad type property
prop = '<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'

eq1 = typeProp == prop  # False
eq2 = len(prop) == len(typeProp) and not prop.find(typeProp)
assert eq1 == eq2, '{} vs {}'.format(eq1, eq2)
```
yields:
```sh
>>> assert eq1 == eq2, '{} vs {}'.format(eq1, eq2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: False vs True
```
Per-char comparison yields the same as inclusion search, but distinct from the equality check, which is confusing:
```python
class Entity(object):
	"""Entity to load RDF tripples"""
	# ATTENTION: type(RDF.type + 'x') is <class 'rdflib.term.URIRef'>, which breaks the str comparison
	#typeProp = '<' + str(RDF.type) + '>'  # N3/quad type property          OK
	typeProp = '<' + RDF.type + '>'  # FAILS str comparison
...
...
            prop = '<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'
            print('extend(), props: \n{}\n{}\neq: {}'.format(prop, Entity.typeProp, prop == Entity.typeProp))
            for i in range(min(len(prop), len(Entity.typeProp))):
                if prop[i] != Entity.typeProp[i]:
                    print('Unequal pos: {}, val: {} ({}) vs {} ({})', i, prop[i], ord(prop[i]), Entity.typeProp[i], ord(Entity.typeProp[i]))
                    break
            else:
                print('len: {} vs {}, eq: {}, index: {}'.format(len(prop), len(Entity.typeProp), prop == Entity.typeProp,
                    prop.find(Entity.typeProp)))
```
yields:
```sh
extend(), props: 
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
eq: False
len: 49 vs 49, eq: False, index: 0
```
Investigating the cause:
```sh
>>> type(prop)
<type 'str'>
>>> type(typeProp)
<class 'rdflib.term.URIRef'>
```

The workaround is to perform the explicit type casting `typeProp = '<' + str(RDF.type) + '>' `, but this is not the appropriate solution for any scripting language. If `rdflib.term.URIRef` performs implicit casting from `str`, then it should also support at least `str` equality comparison operations in proper way.

**Comment by white-gecko** [comment]
We should discuss which behavior is wanted.

**Comment by tgbugs** [comment]
Having explored this at length, there is no good answer here. The behavior is also more extensive than just str URIRef comparisons, subclasses of URIRef cannot be serialized into a graph, only URIRefs. This is probably the sanest behavior, otherwise there are a number of assumptions that the internal serialization code makes that could be violated in ways that lead to extremely hard to track down errors.

On comparison to strings directly, I think that it is probably the right decision to require an explicit caste to string due to the fact that `rdflib.Literal("https://www.example.com/")` and `rdflib.URIRef("https://www.example.com/")` are two very different things. If anything should return `==` to the string form it should be the `Literal` and not the `URIRef`. I don't see any way around this that would produce predictable behavior.

**Comment by white-gecko** [comment]
See https://github.com/RDFLib/rdflib/pull/774#issuecomment-600081214
