### ISSUE TITLE
graph.load is really slow

### ISSUE THREAD

**Issue by tienduccao** [RDFLib/rdflib#776]
I tried to load 1.6 millions triples using `graph.load ` and it took me 3 minutes.
Is there any suggestion to make it faster?

**Comment by joernhees** [comment]
hmm, not really sure if i want to consider that slow, but i'd say that rdflib currently definitely isn't really optimized for speed (and neither are most RDF serialization formats in general). Python isn't the fastest wrt. string parsing, but i think the two main areas of speeding up parsing are the parsers themselves and the store implementations.

Creating special purpose parsers for example for the _canonical_ forms of ntriples, ttl, etc. (the canonical form greatly simplifies parsing and would make it possible to speed it up a lot) has always been on my todo list, but i didn't find the time yet.

Wrt. the stores it heavily depends on what backend you're using, the default (Integer Optimized Memory) not really being the most efficient in terms of size and parsing speed, but rather optimized for later queries.

That said: in the current master branch i optimized the hashing time for all terms (https://github.com/RDFLib/rdflib/commit/2fa4d8be9efb0842af5e82bf768c67fac00038e6), so maybe that is already slightly faster (you can try it out with `pip install https://github.com/RDFLib/rdflib/archive/master.zip`). Otherwise i'd currently suggest using a triple store with bulk import as a backend.

Except from that: contributions always welcome...

**Comment by niklasl** [comment]
I agree with the considerations @joernhees bring up.

In addition to that, it *might* be possible to speed things up for you @tienduccao just by using [PyPy](http://pypy.org/) instead of regular Python. (Sometimes, things are 2-10 times faster, sometimes way slower. Be sure to use the latest release, since recent improvements in PyPy regarding stuff like memory usage and data structures might be just what's needed.)

**Comment by gromgull** [comment]
I've previously written by own "parser" for a quad serialisation that is `<graphuri> <subject> <predicate> <object>` lines, since then you can very easily skip complicated string parsing :) 

It probably has not place in core rdflib though.
