### ISSUE TITLE
README sample code doesn't work with specific pages

### ISSUE THREAD

**Issue by ibrahimsharaf** [RDFLib/rdflib#809]
Hi, I am trying to extract the abstract of a pages via the provided sample code but it is returning an empty list

```
import rdflib

g = rdflib.Graph()
g.load('http://dbpedia.org/resource/Mobile_virus')

db_object = rdflib.URIRef('http://dbpedia.org/resource/Mobile_virus')
dbpedia = rdflib.Namespace('http://dbpedia.org/ontology/')
abstracts = list(x for x in g.objects(db_object, dbpedia['abstract']) if x.language == 'en')

print(abstracts)
```

**Comment by wimmuskee** [comment]
Most likely because the example url you are using does not exist, but it redirecting (301) to Mobile_malware.
If I use 'http://dbpedia.org/resource/Mobile_malware' to load and as object identifier, the example code is working.

RDFlib redirection seems to working. If you load the Mobile_virus uri, but use Mobile_malware for the db_object, the example returns the correct abstract.

**Comment by gjhiggins** [comment]
Answered by [wimmuskee.](https://github.com/wimmuskee)
