### ISSUE TITLE
SHACL or SHEX Implementation

### ISSUE THREAD

**Issue by nicholsn** [RDFLib/rdflib#842]
Is there an implementation of the SHACL or SHEX shape constraint languages on the rdflib roadmap?

**Comment by nicholascar** [comment]
Yes! We (CSIRO, Australia) are coding up a pySHACL SHACL validator and are looking to move that into rdflib. 

Until now there really hasn't been an up-to-date tool for SHACL in Python, only a pre-standard tool Peter Patel-Scheider made that is not obsolete (doesn't follow the spec).

We likely won't make a ShEx validator due to this current validator: https://github.com/hsolbrig/PyShEx

Let me know if you'd like more info about pySHACL (nicholas.car@csiro.au)

**Comment by nicholsn** [comment]
@nicholascar awesome, thanks for sharing that update. pySHACL will be a nice addition to rdflib and thanks for the pointer to PySHEx, I had not seen that.
