### ISSUE TITLE
Any chance to make new release?

### ISSUE THREAD

**Issue by kloczek** [RDFLib/rdflib#925]
I see that at least some python 3 issues has been already fixed in some already committed changes after 4.2.2. I think that it would be good to make new release :)

**Comment by satra** [comment]
The last release of rdflib was almost 3 years back. Is there any timeline for the next release? or a list of what the blockers are.

If this is a resource issue, could a call be made for additional maintainers?

**Comment by nicholascar** [comment]
This question has come up a few times. I'm trying to get a bunch of simple issues closed (many can be but no one's bothered) so we can prepare for a new release by getting our issue tracker (and PRs) in order first.

**Comment by effigies** [comment]
@nicholascar I am *extremely* sympathetic to the impulse to get everything in order, but prioritization is hard without a more concrete goal. Could I suggest making a release candidate so that downstream projects can start testing the pre-release, get a short list of critical issues that prevent upgrade, and start by pushing on those?

I don't have enough experience with RDFLib to be useful here, but if this seems good, I'm happy to harass downstream projects and help them set up tests that run against the release candidate.

**Comment by satra** [comment]
@nicholascar - if we can determine which issues need work, i can get some folks to help out. are the milestones up to date?

also would rdflib 5.0.0 be py3 only (and if so what minimal version 3.5, 3.6?) it seems it would not make sense to release a 2.x compatible version at this point.

**Comment by tgbugs** [comment]
Speaking with a bit of self interest, I would prioritize the outstanding pull requests on the [5.0.0 milestone](https://github.com/RDFLib/rdflib/milestone/2). There are many things that need to be done, but I don't see why they can't be moved to a 6.0.0 release (or 5.1.0) in order to get something out the door for 5.0.0.

It would be possible to drop py2.7 support superficially, but actually rooting out the compatibility layer is a huge undertaking, and is almost certainly not in scope for a 5.0.0 release.

Note that at least some projects have been using my temporary [release](https://pypi.org/project/neurdflib/) of the current master plus [my outstanding pulls](https://github.com/RDFLib/rdflib/pulls/tgbugs).

**Comment by ashleysommer** [comment]
@effigies
While the release team is getting ready to put together the new version, you can install the current rdflib master like:
`pip install "git+https://github.com/RDFLib/rdflib@master#egg=rdflib"`
That way you and others can test your application against latest RDFLib before the new version comes out.

**Comment by nicholascar** [comment]
Good points raised above so let's work out a plan and do it!

@tgbugs Tom, @satra Satrajit, @effigies Chris: please can each of you email me at nick@kurrawong.net so I can do a small amount of coordination by email with @ashleysommer  Ashley and you all? Ashley and perhaps @white-gecko (Natanael) and I will likely take on official repo management shortly.

**Comment by gromgull** [comment]
I'm going to hand over the maintenance hat here, so my opinion shouldn't carry that much weight, but I would go with the planned roadmap: https://groups.google.com/d/msg/rdflib-dev/xNCL20kKi94/HcpWGFnXBQAJ

I.e get the last few PRs merged for 5.0 - stay with removing 2.6 support, but keep 2.7 (we still run several things on 2.7 in production :D) 

Then hopefully have more regular releases from now on!

**Comment by nicholascar** [comment]
@gromgull that roadmap swill looks pretty sensible to me so I think our first planning session will be to reflect on that and update (a couple of the PRs are now merged).

**Comment by nicholascar** [comment]
I'm closing this issue since the timeline for release is set (see https://rdflib.github.io) and it looks like we're going to get there!

I'm keen to get our number of open issues down...
