### ISSUE TITLE
Can't split URIs ending with numbers

### ISSUE THREAD

**Issue by costezki** [RDFLib/rdflib#947]
URIs having numbers in the last segment are perfectly valid and should be allowed. 
The following code reproduces the exception but should, in fact, work just fine. 

```
g = rdflib.Graph()
g.bind("eurovoc", rdflib.Namespace('http://eurovoc.europa.eu/'))
x = g.qname(rdflib.URIRef("http://eurovoc.europa.eu/100141"))
x
```

**Comment by JervenBolleman** [comment]
This is because a XML QName is not allowed to start with a digit. Now of course sparql and turtle allow this kind of prefixing.

This is also tricky for python because the Namespace utils would expect usage like this.
```python
Eurovoc.100141
```
Which is not valid python as variables (and fields) need to start with a digit or underscore.

**Comment by gjhiggins** [comment]
Example no longer causes an Exception, qname is printed as `eurovoc:100141`
